"""add_activation_code_to_users

Revision ID: 984a5f585664
Revises: 7ed3dfc7575a
Create Date: 2026-07-23 23:43:49.221998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984a5f585664'
down_revision: Union[str, Sequence[str], None] = '7ed3dfc7575a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_code', sa.String(length=10), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['activation_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'activation_code')
    # ### end Alembic commands ###
