"""redesign order model

Revision ID: 5f6d7af44310
Revises: 22b1ed2e9612
Create Date: 2026-07-23 11:58:31.926342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f6d7af44310'
down_revision: Union[str, Sequence[str], None] = '22b1ed2e9612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('from_store_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('to_store_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('estimated_weight', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='orderpriority', native_enum=False), nullable=False))
    op.add_column('orders', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('picked_up_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('WAITING_FOR_COURIER', 'ACCEPTED', 'PICKED_UP', 'DELIVERING', 'DELIVERED', 'CANCELED', name='orderstatus', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('orders_store_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'stores', ['to_store_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'stores', ['from_store_id'], ['id'])
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'store_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('delivery_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('customer_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_store_id_fkey'), 'orders', 'stores', ['store_id'], ['id'])
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('WAITING_FOR_COURIER', 'ACCEPTED', 'PICKED_UP', 'DELIVERING', 'DELIVERED', 'CANCELED', name='orderstatus', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('orders', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'picked_up_at')
    op.drop_column('orders', 'accepted_at')
    op.drop_column('orders', 'comment')
    op.drop_column('orders', 'priority')
    op.drop_column('orders', 'estimated_weight')
    op.drop_column('orders', 'description')
    op.drop_column('orders', 'to_store_id')
    op.drop_column('orders', 'from_store_id')
    # ### end Alembic commands ###
