"""add_activation_dates

Revision ID: c97fcdf90e89
Revises: 984a5f585664
Create Date: 2026-07-23 23:52:15.106553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97fcdf90e89'
down_revision: Union[str, Sequence[str], None] = '984a5f585664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'activated_at')
    op.drop_column('users', 'activation_code_expires_at')
    # ### end Alembic commands ###
