"""add courier to orders

Revision ID: fa85ef9ac7a6
Revises: 4e19753f4c61
Create Date: 2026-07-22 20:44:59.417782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa85ef9ac7a6'
down_revision: Union[str, Sequence[str], None] = '4e19753f4c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['courier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'courier_id')
    # ### end Alembic commands ###
